---
AllCops:
  Exclude:
    - 'Rakefile'
    - 'Vagrantfile'
    - 'Policyfile.rb'
    - 'Berksfile'
    - 'Thorfile'
    - 'Gemfile'
    - 'metadata.rb'
    - 'test/**/*'
    - 'bin/**'
    - 'vendor/**/*'
AlignParameters:
  Enabled: false
ClassLength:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
Style/FileName:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
PerceivedComplexity:
  Enabled: false
<<<<<<< 28dd8b7706da63f66649d147adba09341b74c06e
Style/SpaceBeforeFirstArg:
=======
SpaceBeforeFirstArg:
>>>>>>> Update repository with new configuration files.
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FileName:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/ModuleFunction:
<<<<<<< 28dd8b7706da63f66649d147adba09341b74c06e
=======
  Enabled: false
Style/IndentationWidth:
  Enabled: false
Style/IndentArray:
>>>>>>> Update repository with new configuration files.
  Enabled: false
